In [1]:
# Task 1 - Write a program that allows you to enter 4 numbers and stores them in a file called “Numbers”

In [4]:
my_file = open("Numbers", "w")
num1 = 3
num2 = 45
num3 = 83
num4 = 21

my_file.write (str(num1))

my_file.close()

message = "please enter {}, {}, {}, {}".format(num1, num2,num3, num4)

print(message)

please enter 3, 45, 83, 21


In [5]:
mynumbers = list()
for nb in range (1, 5):
    msg = "enter value # {}: " .format (nb)
    inp = int(input(msg))
    mynumbers.append(inp)

print(mynumbers)

[3, 45, 83, 21]


In [6]:
with open("numbers", "w") as f:
    for nb in mynumbers:
        f.write(f"{nb}\n")

In [7]:
my_file.close()

In [8]:


# Task 2 Ask a student for their percentage mark and convert this to a grade

In [9]:
def function_mark_grade():
    per_mark = int(input("Please enter your percentage mark"))
    if per_mark >=80:
        print("Your grade is A")
    elif per_mark >=69:
        print("Your grade is a B")
    elif per_mark >=59:
        print("Your grade is a C")
    elif per_mark >=49:
        print("Your grade is a D")
    elif per_mark >=40:
        print("Your grade is an E")
    elif per_mark >=35:
        print("Your mark in an F")
    else:
        print("Your grade is a U")

In [10]:
function_mark_grade()

Your grade is A


In [11]:


# Task 2 extension - Ask the user for their target grade and print this with their mark

In [12]:
per_mark = int(input("Please enter your percentage mark"))
target_grade = int(input("Please enter your target grade"))
if target_grade < per_mark:
    print("Well done, you have scored above your predicted grade!")
elif target_grade == per_mark:
    print("congratulations you are working at the expected level")
else:
    print("Sorry, you have attained a lower grade than predicted")

Well done, you have scored above your predicted grade!


In [13]:
# Numpy Tasks

# 1 - Create a 1D array of numbers from 0-9

In [14]:
import numpy as np

array = np.array([0,1,2,3,4,5,6,7,8, 9])

print(array)

[0 1 2 3 4 5 6 7 8 9]


In [15]:

# 2 - Create a 3×3 NumPy array of all Boolean value Trues

In [16]:
import numpy as np

array = np.array([2,4,6,8,10,12,14,16,18])

newarray = array.reshape(3,3)

print(newarray)

[[ 2  4  6]
 [ 8 10 12]
 [14 16 18]]


In [17]:
newarray % 2==0

array([[ True,  True,  True],
       [ True,  True,  True],
       [ True,  True,  True]])

In [18]:


#3 Extract all odd numbers from array of 1 to 10

In [19]:
import numpy as np

array = np.array([1,2,3,4,5,6,7,8,9,10])

print(array[0::2])

[1 3 5 7 9]


In [ ]:


#4 Replace all odd numbers in an array of 1-10 with the value -1

In [20]:
array[0::2] = -1
print(array)

[-1  2 -1  4 -1  6 -1  8 -1 10]


In [ ]:
#5 Convert a 1D array to a 2D array with 2 rows

In [21]:
import numpy as np

array = np.array([1,2,3,4,5,6,7,8,9,10])

newarray = array.reshape(2,5)

print(newarray)

[[ 1  2  3  4  5]
 [ 6  7  8  9 10]]


In [22]:


#6 Create two arrays a and b, stack these two arrays vertically use the np.dot and np.sum to calculate totals

In [23]:
import numpy as np

a = np.arange (19, 28).reshape (3,3)
b = np.arange (59, 68).reshape (3,3)
t = np.dot(a,b)
print(t)

[[3726 3786 3846]
 [4284 4353 4422]
 [4842 4920 4998]]


In [24]:
import numpy as np

a = np.arange (19, 28).reshape (3,3)
b = np.arange (59, 68).reshape (3,3)
t = np.dot(a,b)
sum = np.sum(t)
print(sum)

39177
